server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - monitoring
    paths:
      - path: /prometheus
        pathType: Prefix
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /

# The job must point to the service name of the API inside api/deployment.yaml
extraScrapeConfigs: |
  - job_name: 'pipeline-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['pipeline-api-service.default.svc.cluster.local'] 
        labels:
          group: 'pipeline-api'