ingress:
  enabled: true
  ingressClassName: nginx
  path: /grafana
  hosts:
    - monitoring

grafana.ini:
  server:
    domain: monitoring
    root_url: http://monitoring:30123/grafana
    serve_from_sub_path: true

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring:80
        access: proxy

sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard